export const types = {
    GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_ERROR: 'GET_USERS_ERROR',

    GET_USER_REQUESTED: 'GET_USER_REQUESTED',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',

    GET_POSTS_REQUESTED: 'GET_POSTS_REQUESTED',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_ERROR: 'GET_POSTS_ERROR',
}

